const EVENT_TYPES = {
    CHECKOUT_STARTED: 'CHECKOUT_STARTED',
    ORDER_PAID: 'ORDER_PAID',
    BROADCAST_STARTED: 'BROADCAST_STARTED',
    SUPPORT_CLIENT_MESSAGE: 'SUPPORT_CLIENT_MESSAGE',
    SUPPORT_MANAGER_REPLY: 'SUPPORT_MANAGER_REPLY'
};

module.exports = {
    EVENT_TYPES
};

